// <auto-generated />
using Microservicio_Cuestionario.AccessData.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Microservicio_Cuestionario.AccessData.Migrations
{
    [DbContext(typeof(GenericContext))]
    partial class GenericContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microservicio_Cuestionario.Domain.Entities.Cuestionario", b =>
                {
                    b.Property<int>("CuestionarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClaseId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("CuestionarioID");

                    b.ToTable("Cuestionarios");

                    b.HasData(
                        new
                        {
                            CuestionarioID = 1,
                            ClaseId = 1,
                            Descripcion = "Cuestionario de POO"
                        },
                        new
                        {
                            CuestionarioID = 2,
                            ClaseId = 2,
                            Descripcion = "Cuestionario de Manejo de excepciones"
                        },
                        new
                        {
                            CuestionarioID = 3,
                            ClaseId = 3,
                            Descripcion = "Cuestionario de Grafos"
                        },
                        new
                        {
                            CuestionarioID = 4,
                            ClaseId = 4,
                            Descripcion = "Cuestionario de verbo to be"
                        },
                        new
                        {
                            CuestionarioID = 5,
                            ClaseId = 5,
                            Descripcion = "Cuestionario de Presente Simple"
                        },
                        new
                        {
                            CuestionarioID = 6,
                            ClaseId = 6,
                            Descripcion = "Completa las sentencias usando Presente Continuo"
                        },
                        new
                        {
                            CuestionarioID = 7,
                            ClaseId = 7,
                            Descripcion = "Cuestionario de Campo eléctrico"
                        },
                        new
                        {
                            CuestionarioID = 8,
                            ClaseId = 8,
                            Descripcion = "Cuestinario de Campo Magnético"
                        },
                        new
                        {
                            CuestionarioID = 9,
                            ClaseId = 9,
                            Descripcion = "Cuestionario de Ecuaciones de Maxwell"
                        },
                        new
                        {
                            CuestionarioID = 10,
                            ClaseId = 10,
                            Descripcion = "Cuestionario Patrones de Diseño"
                        },
                        new
                        {
                            CuestionarioID = 11,
                            ClaseId = 11,
                            Descripcion = "Introducción al Chino Mandarin"
                        });
                });

            modelBuilder.Entity("Microservicio_Cuestionario.Domain.Entities.Pregunta", b =>
                {
                    b.Property<int>("PreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CalificacionParcial")
                        .HasColumnType("float");

                    b.Property<int>("CuestionarioId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("PreguntaId");

                    b.HasIndex("CuestionarioId");

                    b.ToTable("Preguntas");

                    b.HasData(
                        new
                        {
                            PreguntaId = 1,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 1,
                            Descripcion = "¿Que es la Encapsulación?"
                        },
                        new
                        {
                            PreguntaId = 2,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 1,
                            Descripcion = "¿Que son las Interfaces?"
                        },
                        new
                        {
                            PreguntaId = 3,
                            CalificacionParcial = 4.0,
                            CuestionarioId = 1,
                            Descripcion = "¿Que es Sobrecarga?"
                        },
                        new
                        {
                            PreguntaId = 4,
                            CalificacionParcial = 2.0,
                            CuestionarioId = 2,
                            Descripcion = "¿Qué es una excepción?"
                        },
                        new
                        {
                            PreguntaId = 5,
                            CalificacionParcial = 4.0,
                            CuestionarioId = 2,
                            Descripcion = "Un programador, ¿puede disparar sus propias excepciones?"
                        },
                        new
                        {
                            PreguntaId = 6,
                            CalificacionParcial = 2.0,
                            CuestionarioId = 2,
                            Descripcion = "¿Qué se define dentro del finally?"
                        },
                        new
                        {
                            PreguntaId = 7,
                            CalificacionParcial = 2.0,
                            CuestionarioId = 2,
                            Descripcion = "¿Qué se puede hacer con la sentencia trow?"
                        },
                        new
                        {
                            PreguntaId = 8,
                            CalificacionParcial = 4.0,
                            CuestionarioId = 3,
                            Descripcion = "Según la definición de Grafos, indice cual opción define mejor el concepto de trayectoria de un vértice v0 a vn."
                        },
                        new
                        {
                            PreguntaId = 9,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 3,
                            Descripcion = "Indique la definición correcta de Grafo."
                        },
                        new
                        {
                            PreguntaId = 10,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 3,
                            Descripcion = "¿Cuál es el algoritmo que resuelve el problema del camino mínimo?"
                        },
                        new
                        {
                            PreguntaId = 11,
                            CalificacionParcial = 4.0,
                            CuestionarioId = 4,
                            Descripcion = "Complete: ___________ in the office?"
                        },
                        new
                        {
                            PreguntaId = 12,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 4,
                            Descripcion = "Complete: _______ the books on the shelf?"
                        },
                        new
                        {
                            PreguntaId = 13,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 4,
                            Descripcion = "Complete: I ____ not ready."
                        },
                        new
                        {
                            PreguntaId = 14,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 5,
                            Descripcion = "Complete: She ______ (wash) her car every week? "
                        },
                        new
                        {
                            PreguntaId = 15,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 5,
                            Descripcion = "Complete: Paul _______ (sleep) seven hours a day."
                        },
                        new
                        {
                            PreguntaId = 16,
                            CalificacionParcial = 4.0,
                            CuestionarioId = 5,
                            Descripcion = "Complete: Who _____ (be) your favourite football player? "
                        },
                        new
                        {
                            PreguntaId = 17,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 6,
                            Descripcion = "Complete: She _________ (leave) tomorrow morning."
                        },
                        new
                        {
                            PreguntaId = 18,
                            CalificacionParcial = 4.0,
                            CuestionarioId = 6,
                            Descripcion = "Complete: You _______ (make) a great effort."
                        },
                        new
                        {
                            PreguntaId = 19,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 6,
                            Descripcion = "Complete: I _______ (watch) TV right now."
                        },
                        new
                        {
                            PreguntaId = 20,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 7,
                            Descripcion = "El campo eléctrico es:"
                        },
                        new
                        {
                            PreguntaId = 21,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 7,
                            Descripcion = "¿Qué es un solenoide?"
                        },
                        new
                        {
                            PreguntaId = 22,
                            CalificacionParcial = 4.0,
                            CuestionarioId = 7,
                            Descripcion = "¿Qué es un electroimán?"
                        },
                        new
                        {
                            PreguntaId = 23,
                            CalificacionParcial = 4.0,
                            CuestionarioId = 8,
                            Descripcion = "¿Qué es la Coercitividad?"
                        },
                        new
                        {
                            PreguntaId = 24,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 8,
                            Descripcion = "¿Qué es la Remanencia?"
                        },
                        new
                        {
                            PreguntaId = 25,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 8,
                            Descripcion = "El vacío, ¿Tiene Coercitividad?"
                        },
                        new
                        {
                            PreguntaId = 26,
                            CalificacionParcial = 4.0,
                            CuestionarioId = 9,
                            Descripcion = "¿A qué se conoce como ecuaciones de Maxwell?."
                        },
                        new
                        {
                            PreguntaId = 27,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 9,
                            Descripcion = "¿Cuál de los siguientes parámetros no interviene en las ecuaciones de Maxwell?"
                        },
                        new
                        {
                            PreguntaId = 28,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 9,
                            Descripcion = "¿Qué sucede con el valor del Flujo si duplicamos el valor de la carga?"
                        },
                        new
                        {
                            PreguntaId = 29,
                            CalificacionParcial = 2.0,
                            CuestionarioId = 10,
                            Descripcion = "¿Qué es un patrón de diseño?"
                        },
                        new
                        {
                            PreguntaId = 30,
                            CalificacionParcial = 4.0,
                            CuestionarioId = 10,
                            Descripcion = "¿Cuál de los siguientes no es un tipo de patrón de diseño?"
                        },
                        new
                        {
                            PreguntaId = 31,
                            CalificacionParcial = 4.0,
                            CuestionarioId = 10,
                            Descripcion = "El patrón que soluciona los problemas de composición de clases y objetos es:"
                        },
                        new
                        {
                            PreguntaId = 32,
                            CalificacionParcial = 4.0,
                            CuestionarioId = 11,
                            Descripcion = "Qué significa: 谢谢!."
                        },
                        new
                        {
                            PreguntaId = 33,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 11,
                            Descripcion = "Qué significa: 不用谢."
                        },
                        new
                        {
                            PreguntaId = 34,
                            CalificacionParcial = 3.0,
                            CuestionarioId = 11,
                            Descripcion = "Qué significa: 你好."
                        });
                });

            modelBuilder.Entity("Microservicio_Cuestionario.Domain.Entities.Registro", b =>
                {
                    b.Property<int>("RegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Calificacion")
                        .HasColumnType("real");

                    b.Property<int>("CuestionarioId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.HasKey("RegistroId");

                    b.HasIndex("CuestionarioId");

                    b.ToTable("Registros");
                });

            modelBuilder.Entity("Microservicio_Cuestionario.Domain.Entities.Respuesta", b =>
                {
                    b.Property<int>("RespuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<bool>("Flag")
                        .HasColumnType("bit");

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.HasKey("RespuestaId");

                    b.HasIndex("PreguntaId");

                    b.ToTable("Respuestas");

                    b.HasData(
                        new
                        {
                            RespuestaId = 1,
                            Descripcion = "Es la capacidad que tienen los objetos de comportarse de múltiples formas recurriendo a la herencia.",
                            Flag = false,
                            PreguntaId = 1
                        },
                        new
                        {
                            RespuestaId = 2,
                            Descripcion = "Es la forma de proteger u ocultar las propiedades de un objetos, estableciendo los permisos y niveles de visibilidad.",
                            Flag = true,
                            PreguntaId = 1
                        },
                        new
                        {
                            RespuestaId = 3,
                            Descripcion = "Es un evento que ocurre durante la ejecucion del programa, interrumpiendo el flujo normal.",
                            Flag = false,
                            PreguntaId = 1
                        },
                        new
                        {
                            RespuestaId = 4,
                            Descripcion = "Las interfaces definen lo que una clase que la implemente debe hacer.",
                            Flag = true,
                            PreguntaId = 2
                        },
                        new
                        {
                            RespuestaId = 5,
                            Descripcion = "Es la capacidad que tienen los objetos de comportarse de múltiples formas recurriendo a la herencia.",
                            Flag = false,
                            PreguntaId = 2
                        },
                        new
                        {
                            RespuestaId = 6,
                            Descripcion = "Es la base de la reutilización del código, obteniendo la información de sus superclases.",
                            Flag = false,
                            PreguntaId = 2
                        },
                        new
                        {
                            RespuestaId = 7,
                            Descripcion = "Consiste en tener dos o más métodos con distinto nombre pero los mismos parámetros.",
                            Flag = false,
                            PreguntaId = 3
                        },
                        new
                        {
                            RespuestaId = 8,
                            Descripcion = "Consiste en tener dos o más métodos con el mismo nombre pero diferentes parámetros.",
                            Flag = true,
                            PreguntaId = 3
                        },
                        new
                        {
                            RespuestaId = 9,
                            Descripcion = "Es un evento que ocurre durante la ejecución de un programa y que provoca que los ciclos no puedan terminarse.",
                            Flag = false,
                            PreguntaId = 4
                        },
                        new
                        {
                            RespuestaId = 10,
                            Descripcion = "Es un evento que ocurre durante la ejecución de un programa y que interrumpe el flujo normal de operación.",
                            Flag = true,
                            PreguntaId = 4
                        },
                        new
                        {
                            RespuestaId = 11,
                            Descripcion = "No.",
                            Flag = false,
                            PreguntaId = 5
                        },
                        new
                        {
                            RespuestaId = 12,
                            Descripcion = "Sí.",
                            Flag = true,
                            PreguntaId = 5
                        },
                        new
                        {
                            RespuestaId = 13,
                            Descripcion = "El código que se ejecuta cuando haya excepciones.",
                            Flag = false,
                            PreguntaId = 6
                        },
                        new
                        {
                            RespuestaId = 14,
                            Descripcion = "El código que se ejecutará haya o no excepciones.",
                            Flag = true,
                            PreguntaId = 6
                        },
                        new
                        {
                            RespuestaId = 15,
                            Descripcion = "El código que captura y maneja el código que se lance la excepción.",
                            Flag = false,
                            PreguntaId = 6
                        },
                        new
                        {
                            RespuestaId = 16,
                            Descripcion = "Se puede identificar un error al cual posteriormente aplicar una excepción.",
                            Flag = false,
                            PreguntaId = 7
                        },
                        new
                        {
                            RespuestaId = 17,
                            Descripcion = "Se puede utilizar para disparar una excepción.",
                            Flag = true,
                            PreguntaId = 7
                        },
                        new
                        {
                            RespuestaId = 18,
                            Descripcion = "Se puede utilizar para señalar un código y no lanzar una excepción si este tiene problemas.",
                            Flag = false,
                            PreguntaId = 7
                        },
                        new
                        {
                            RespuestaId = 19,
                            Descripcion = "Un camino consecutivo de aristas consecutivas desde v0 hasta vn.",
                            Flag = false,
                            PreguntaId = 8
                        },
                        new
                        {
                            RespuestaId = 20,
                            Descripcion = "Es un camino de nodos alternantes desde v0 hasta vn.",
                            Flag = false,
                            PreguntaId = 8
                        },
                        new
                        {
                            RespuestaId = 21,
                            Descripcion = "Es una sucesión de longitud n, alternante de n+1 vértices y n aristas que comienza en v0 y termina en vn.",
                            Flag = true,
                            PreguntaId = 8
                        },
                        new
                        {
                            RespuestaId = 22,
                            Descripcion = "Es un conjunto de n-1 nodos alternantes y consecutivos desde v0 hasta vn.",
                            Flag = false,
                            PreguntaId = 8
                        },
                        new
                        {
                            RespuestaId = 23,
                            Descripcion = "Un conjunto de vértices y aristas, tal que cada arista está asociada a un par.",
                            Flag = true,
                            PreguntaId = 9
                        },
                        new
                        {
                            RespuestaId = 24,
                            Descripcion = "Un diagrama compuesto de nodos y conexiones.",
                            Flag = false,
                            PreguntaId = 9
                        },
                        new
                        {
                            RespuestaId = 25,
                            Descripcion = "Un gráfico matemático que se emplea para modelar problemas de la vida real.",
                            Flag = false,
                            PreguntaId = 9
                        },
                        new
                        {
                            RespuestaId = 26,
                            Descripcion = "Múltiples nodos denominados vértices y caminos denominados marcos.",
                            Flag = false,
                            PreguntaId = 9
                        },
                        new
                        {
                            RespuestaId = 27,
                            Descripcion = "El algoritmo de VanVourer.",
                            Flag = false,
                            PreguntaId = 10
                        },
                        new
                        {
                            RespuestaId = 28,
                            Descripcion = "El algoritmo de Dijkstra.",
                            Flag = true,
                            PreguntaId = 10
                        },
                        new
                        {
                            RespuestaId = 29,
                            Descripcion = "El algoritmo de Gauss.",
                            Flag = false,
                            PreguntaId = 10
                        },
                        new
                        {
                            RespuestaId = 30,
                            Descripcion = "When is",
                            Flag = true,
                            PreguntaId = 11
                        },
                        new
                        {
                            RespuestaId = 31,
                            Descripcion = "Who is",
                            Flag = false,
                            PreguntaId = 11
                        },
                        new
                        {
                            RespuestaId = 32,
                            Descripcion = "Where is",
                            Flag = false,
                            PreguntaId = 11
                        },
                        new
                        {
                            RespuestaId = 33,
                            Descripcion = "Isn't",
                            Flag = false,
                            PreguntaId = 12
                        },
                        new
                        {
                            RespuestaId = 34,
                            Descripcion = "Are",
                            Flag = true,
                            PreguntaId = 12
                        },
                        new
                        {
                            RespuestaId = 35,
                            Descripcion = "Was",
                            Flag = false,
                            PreguntaId = 12
                        },
                        new
                        {
                            RespuestaId = 36,
                            Descripcion = "am",
                            Flag = true,
                            PreguntaId = 13
                        },
                        new
                        {
                            RespuestaId = 37,
                            Descripcion = "is not",
                            Flag = false,
                            PreguntaId = 13
                        },
                        new
                        {
                            RespuestaId = 38,
                            Descripcion = "where",
                            Flag = false,
                            PreguntaId = 13
                        },
                        new
                        {
                            RespuestaId = 39,
                            Descripcion = "are",
                            Flag = false,
                            PreguntaId = 13
                        },
                        new
                        {
                            RespuestaId = 40,
                            Descripcion = "washies",
                            Flag = false,
                            PreguntaId = 14
                        },
                        new
                        {
                            RespuestaId = 41,
                            Descripcion = "washes",
                            Flag = true,
                            PreguntaId = 14
                        },
                        new
                        {
                            RespuestaId = 42,
                            Descripcion = "washs",
                            Flag = false,
                            PreguntaId = 14
                        },
                        new
                        {
                            RespuestaId = 43,
                            Descripcion = "sleep",
                            Flag = false,
                            PreguntaId = 15
                        },
                        new
                        {
                            RespuestaId = 44,
                            Descripcion = "sleeps",
                            Flag = true,
                            PreguntaId = 15
                        },
                        new
                        {
                            RespuestaId = 45,
                            Descripcion = "sleepes",
                            Flag = false,
                            PreguntaId = 15
                        },
                        new
                        {
                            RespuestaId = 46,
                            Descripcion = "am",
                            Flag = false,
                            PreguntaId = 16
                        },
                        new
                        {
                            RespuestaId = 47,
                            Descripcion = "are",
                            Flag = false,
                            PreguntaId = 16
                        },
                        new
                        {
                            RespuestaId = 48,
                            Descripcion = "is",
                            Flag = true,
                            PreguntaId = 16
                        },
                        new
                        {
                            RespuestaId = 49,
                            Descripcion = "leaving",
                            Flag = false,
                            PreguntaId = 17
                        },
                        new
                        {
                            RespuestaId = 50,
                            Descripcion = "is leaving",
                            Flag = true,
                            PreguntaId = 17
                        },
                        new
                        {
                            RespuestaId = 51,
                            Descripcion = "leaved",
                            Flag = false,
                            PreguntaId = 17
                        },
                        new
                        {
                            RespuestaId = 52,
                            Descripcion = "are making",
                            Flag = false,
                            PreguntaId = 18
                        },
                        new
                        {
                            RespuestaId = 53,
                            Descripcion = "is making",
                            Flag = true,
                            PreguntaId = 18
                        },
                        new
                        {
                            RespuestaId = 54,
                            Descripcion = "is make",
                            Flag = false,
                            PreguntaId = 18
                        },
                        new
                        {
                            RespuestaId = 55,
                            Descripcion = "do watching",
                            Flag = false,
                            PreguntaId = 19
                        },
                        new
                        {
                            RespuestaId = 56,
                            Descripcion = "are watching",
                            Flag = false,
                            PreguntaId = 19
                        },
                        new
                        {
                            RespuestaId = 57,
                            Descripcion = "am watching",
                            Flag = true,
                            PreguntaId = 19
                        },
                        new
                        {
                            RespuestaId = 58,
                            Descripcion = "Es una cantidad escalar muy fácil de calcular.",
                            Flag = false,
                            PreguntaId = 20
                        },
                        new
                        {
                            RespuestaId = 59,
                            Descripcion = "Se define como la fuerza por unidad de carga en un punto dado.",
                            Flag = false,
                            PreguntaId = 20
                        },
                        new
                        {
                            RespuestaId = 60,
                            Descripcion = "Es un campo vectorial y sus unidades son newtons/coulombs.",
                            Flag = true,
                            PreguntaId = 20
                        },
                        new
                        {
                            RespuestaId = 61,
                            Descripcion = "Es un concepto de poca utilidad en electrostática.",
                            Flag = false,
                            PreguntaId = 21
                        },
                        new
                        {
                            RespuestaId = 62,
                            Descripcion = "Es un conjunto de espiras conectadas eléctricamente, a la manera de un resorte comprimido.",
                            Flag = true,
                            PreguntaId = 21
                        },
                        new
                        {
                            RespuestaId = 63,
                            Descripcion = "Es un “anillo” conductor por el que circula la corriente eléctrica.",
                            Flag = false,
                            PreguntaId = 21
                        },
                        new
                        {
                            RespuestaId = 64,
                            Descripcion = "Es una línea de campo eléctrico siempre paralela a la superficies. ",
                            Flag = false,
                            PreguntaId = 22
                        },
                        new
                        {
                            RespuestaId = 65,
                            Descripcion = "Es un campo físico que se representa por medio de un modelo que describe la interacción entre cuerpos.",
                            Flag = false,
                            PreguntaId = 22
                        },
                        new
                        {
                            RespuestaId = 66,
                            Descripcion = "Es un imán no permanente cuya acción dura mientras se produce el pasaje de la corriente por el solenoide.",
                            Flag = true,
                            PreguntaId = 22
                        },
                        new
                        {
                            RespuestaId = 67,
                            Descripcion = "Es el equivalente de la resistencia en los circuitos eléctricos.",
                            Flag = false,
                            PreguntaId = 23
                        },
                        new
                        {
                            RespuestaId = 68,
                            Descripcion = "Es el equivalente de la resistencia en los circuitos magnéticos.",
                            Flag = false,
                            PreguntaId = 23
                        },
                        new
                        {
                            RespuestaId = 69,
                            Descripcion = "Es la facilidad con que un material inducido, adquiere las propiedades del material inductor. En definitiva es la facilidad que tiene una sustancia de magnetizarse.",
                            Flag = true,
                            PreguntaId = 23
                        },
                        new
                        {
                            RespuestaId = 70,
                            Descripcion = "Cuestinario de Campo Magnético.",
                            Flag = false,
                            PreguntaId = 24
                        },
                        new
                        {
                            RespuestaId = 71,
                            Descripcion = "Es el tiempo que dura magnetizada una sustancia.",
                            Flag = true,
                            PreguntaId = 24
                        },
                        new
                        {
                            RespuestaId = 72,
                            Descripcion = "Es el valor de la temperatura en el que la sustancia pierde su propiedad Ferromagnética.",
                            Flag = false,
                            PreguntaId = 24
                        },
                        new
                        {
                            RespuestaId = 73,
                            Descripcion = "Sí",
                            Flag = false,
                            PreguntaId = 25
                        },
                        new
                        {
                            RespuestaId = 74,
                            Descripcion = "No.",
                            Flag = true,
                            PreguntaId = 25
                        },
                        new
                        {
                            RespuestaId = 75,
                            Descripcion = "A veces.",
                            Flag = false,
                            PreguntaId = 25
                        },
                        new
                        {
                            RespuestaId = 76,
                            Descripcion = "Al conjunto de ecuaciones que describen todos los fenómenos eléctricos.",
                            Flag = false,
                            PreguntaId = 26
                        },
                        new
                        {
                            RespuestaId = 77,
                            Descripcion = "Al conjunto fundamental de ecuaciones que describen todos los fenómenos electromagnéticos.",
                            Flag = true,
                            PreguntaId = 26
                        },
                        new
                        {
                            RespuestaId = 78,
                            Descripcion = "Al conjunto de ecuaciones que describen todos los fenómenos magnéticos.",
                            Flag = false,
                            PreguntaId = 26
                        },
                        new
                        {
                            RespuestaId = 79,
                            Descripcion = "El campo gravitatorio.",
                            Flag = true,
                            PreguntaId = 27
                        },
                        new
                        {
                            RespuestaId = 80,
                            Descripcion = "El campo magnético.",
                            Flag = false,
                            PreguntaId = 27
                        },
                        new
                        {
                            RespuestaId = 81,
                            Descripcion = "El campo eléctrico.",
                            Flag = false,
                            PreguntaId = 27
                        },
                        new
                        {
                            RespuestaId = 82,
                            Descripcion = "Se anula.",
                            Flag = false,
                            PreguntaId = 28
                        },
                        new
                        {
                            RespuestaId = 83,
                            Descripcion = "Se duplica.",
                            Flag = true,
                            PreguntaId = 28
                        },
                        new
                        {
                            RespuestaId = 84,
                            Descripcion = "Se reduce a la mitad.",
                            Flag = false,
                            PreguntaId = 28
                        },
                        new
                        {
                            RespuestaId = 85,
                            Descripcion = "Son unas técnicas para resolver problemas comunes en el desarrollo de software.",
                            Flag = true,
                            PreguntaId = 29
                        },
                        new
                        {
                            RespuestaId = 86,
                            Descripcion = "Son pasos para resolver problemas en un lenguaje específico.",
                            Flag = false,
                            PreguntaId = 29
                        },
                        new
                        {
                            RespuestaId = 87,
                            Descripcion = "El patrón creacional.",
                            Flag = false,
                            PreguntaId = 30
                        },
                        new
                        {
                            RespuestaId = 88,
                            Descripcion = "El patrón de comportamiento.",
                            Flag = false,
                            PreguntaId = 30
                        },
                        new
                        {
                            RespuestaId = 89,
                            Descripcion = "El patrón de arquitectura.",
                            Flag = true,
                            PreguntaId = 30
                        },
                        new
                        {
                            RespuestaId = 90,
                            Descripcion = "El patrón creacional.",
                            Flag = false,
                            PreguntaId = 31
                        },
                        new
                        {
                            RespuestaId = 91,
                            Descripcion = "El patrón estructural.",
                            Flag = true,
                            PreguntaId = 31
                        },
                        new
                        {
                            RespuestaId = 92,
                            Descripcion = "El patrón de comportamiento.",
                            Flag = false,
                            PreguntaId = 31
                        },
                        new
                        {
                            RespuestaId = 93,
                            Descripcion = "Buen dia!.",
                            Flag = false,
                            PreguntaId = 32
                        },
                        new
                        {
                            RespuestaId = 94,
                            Descripcion = "¡Gracias!.",
                            Flag = true,
                            PreguntaId = 32
                        },
                        new
                        {
                            RespuestaId = 95,
                            Descripcion = "Hola!.",
                            Flag = false,
                            PreguntaId = 32
                        },
                        new
                        {
                            RespuestaId = 96,
                            Descripcion = "!Gracias!.",
                            Flag = false,
                            PreguntaId = 33
                        },
                        new
                        {
                            RespuestaId = 97,
                            Descripcion = "De nada.",
                            Flag = true,
                            PreguntaId = 33
                        },
                        new
                        {
                            RespuestaId = 98,
                            Descripcion = "Hola.",
                            Flag = false,
                            PreguntaId = 33
                        },
                        new
                        {
                            RespuestaId = 99,
                            Descripcion = "Muy bien.",
                            Flag = false,
                            PreguntaId = 34
                        },
                        new
                        {
                            RespuestaId = 100,
                            Descripcion = "Hola.",
                            Flag = true,
                            PreguntaId = 34
                        },
                        new
                        {
                            RespuestaId = 101,
                            Descripcion = "Adiós.",
                            Flag = false,
                            PreguntaId = 34
                        });
                });

            modelBuilder.Entity("Microservicio_Cuestionario.Domain.Entities.Pregunta", b =>
                {
                    b.HasOne("Microservicio_Cuestionario.Domain.Entities.Cuestionario", "CuestionarioNavegator")
                        .WithMany("PreguntaNavegator")
                        .HasForeignKey("CuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microservicio_Cuestionario.Domain.Entities.Registro", b =>
                {
                    b.HasOne("Microservicio_Cuestionario.Domain.Entities.Cuestionario", "Cuestionario")
                        .WithMany("Registros")
                        .HasForeignKey("CuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microservicio_Cuestionario.Domain.Entities.Respuesta", b =>
                {
                    b.HasOne("Microservicio_Cuestionario.Domain.Entities.Pregunta", "PreguntaNavegator")
                        .WithMany("RespuestaNavegator")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
